### ISSUE TITLE
Missing device ID

### ISSUE THREAD

**Issue by RadioactivePlays** [morrownr/8812au-20210820#18]
There's an adapter based on this chipset (RTL8812AU) from a brand called Intelbras that I believe to be an whitelabeled version of Tenda U12 adapters. **lsusb** shows the following: ```Bus 003 Device 002: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter```.

The PCB design number is the same of a Tenda U12 so I think they are basically the same thing with a different Vendor/DeviceID. It is widespread in Brazil so I think it might be good for people who stumble on this repo to know it is supported.

**Tenda U12:** [Website](https://www.tendacn.com/br/product/u12.html)
![image](https://github.com/morrownr/8812au-20210820/assets/19830027/de33b33b-11f8-40fc-99e4-d1e972bc211a)

**Intelbras ACtion A1200:** [Website](https://www.intelbras.com/pt-br/adaptador-usb-wireless-dual-band-action-a1200)
![image](https://github.com/morrownr/8812au-20210820/assets/19830027/0ee8234e-ef03-48fb-b611-b7210f47451d)

**Comment by morrownr** [comment]
Hi @RadioactivePlays 

ID 0bda:8812 is already in this driver. Do you want me to add it to `Compatible Devices` in the README?

Thanks

**Comment by RadioactivePlays** [comment]
Yeah that's what I meant to say, sorry. I should have made a PR.

**Comment by morrownr** [comment]
Okay, I made the change locally and it will go into the repo soon.
