### ISSUE TITLE
Add support for [Bus 001 Device 008: ID 2357:011f TP-Link 802.11ac WLAN Adapter]

### ISSUE THREAD

**Issue by Taniyan1015** [morrownr/8812au-20210820#29]
I appreciate this project because some PCs do not have Wi-Fi interface.

I checked the current support status by "supported-device-IDs", but I didn't have a hardware ID. 
I apologize for the inconvenience, but could you please add a hardware ID to your project ?

Thanks
Taniyan1015

**Comment by morrownr** [comment]
Hi @Taniyan1015 

You are looking at the wrong driver. Try:

https://github.com/morrownr/8821au-20210708

There is also a test version that is going upstream soon. I can put you on it if you want.
