### ISSUE TITLE
RTC Installation issues.

### ISSUE THREAD

**Issue by Graymann2024** [morrownr/8812au-20210820#33]
Hello, I need help with a RTC DS3231 real-time chip installation on my Raspberry Pi 3+ under Kali: kali-linux-2024.2-raspberry-pi-armhf.img. any and all help with the installation is greatly appreciated.

**Comment by morrownr** [comment]
Hi @Graymann2024 

This repo is for support of the contained rtl8812au Linux driver, not for the installation of a time chip on a RasPi. If there is a problem with the driver in this repo, please elaborate.

**Comment by Graymann2024** [comment]
Hello, I appreciate your statement and question and after following your instructions on how to load the rtl8812au under Kali, it works perfectly.

**Comment by morrownr** [comment]
Sounds good.
